### ISSUE TITLE
Broken maven dependencies

### ISSUE THREAD

**Issue by sgdc3** [BlurEngine/Blur#1]

**Comment by SupaHam** [comment]
Which dependencies?

**Comment by sgdc3** [comment]
All of them, i particular your bukkit commons lib (which is built with gradle so i'm unable to automatically deploy it to a working mvn repo).

**Comment by sgdc3** [comment]
I managed to fix the other deps on my fork.

**Comment by sgdc3** [comment]
Whoops I've forgot to push changes xD srry

**Comment by SupaHam** [comment]
I'll need some time to figure out the repo for my commons lib. For now, if you have Gradle installed you can install it to your maven repo by typing `./gradlew install` in the root dir of SupaCommons.

**Comment by sgdc3** [comment]
Yeah but this scope doesn't work with the jenkins built-in mvn repo :/

**Comment by SupaHam** [comment]
Sorry, this was assuming you were willing to git pull the repo from https://github.com/supaham/supacommons.

**Comment by sgdc3** [comment]
output of a clean blur build: http://ci.xephi.fr/job/Blur/

**Comment by SupaHam** [comment]
Yeah, so sadly you'll have to wait for me to figure this out.

**Comment by sgdc3** [comment]
spigot api is no longer avariable from the selected repos

**Comment by SupaHam** [comment]
Spigot-API is something you have to build yourself, and that's not something I can control. Check out https://www.spigotmc.org/wiki/buildtools/.

**Comment by sgdc3** [comment]
spigotapi is 100% legal, open source and free. Only the implementation can't be distributed.

**Comment by SupaHam** [comment]
Oops I accidently forgot to add the spigot repo, my bad.

**Comment by sgdc3** [comment]
Lol ;)

**Comment by sgdc3** [comment]
https://www.spigotmc.org/wiki/spigot-maven/

**Comment by SupaHam** [comment]
Should be fixed now.

**Comment by sgdc3** [comment]
Ok, new log: http://ci.xephi.fr/job/Blur/3/console
Why 1.8.7 and not 1.8.8?

**Comment by SupaHam** [comment]
No specific reason, it's what I started with. As far as I know there's no difference between 1.8.7 and 1.8.8, but if it's an issue I can bump it up.

**Comment by sgdc3** [comment]
Ok, i was just curious ;)

**Comment by SupaHam** [comment]
Alright, commons library should now be available to you, just rebuild maven, or refresh in your IDE.

**Comment by sgdc3** [comment]
Thanks ;)

**Comment by sgdc3** [comment]
Nope, still unavariable

**Comment by sgdc3** [comment]
@SupaHam

**Comment by sgdc3** [comment]
I purged the entire maven cache but nothing, it doesn't work

**Comment by SupaHam** [comment]
I was just testing you! It should really work now :P

**Comment by sgdc3** [comment]
:P
